### ISSUE TITLE
(Frontend) Reimplementación vista carrito de compras

### ISSUE THREAD

**Issue by enlorca** [Klauditha/desafio_proyecto_final#211]

**Comment by Klauditha** [comment]
@enlorca creo que esto estaba listo le hice unos cambios de estilo a los botones , no se que faltaba



![Image](https://github.com/Klauditha/desafio_proyecto_final/assets/3738243/874bdc4c-05d4-4da5-9f44-2c92094ade9b)

**Comment by enlorca** [comment]
@Klauditha Se ve super!
