### ISSUE TITLE
Wishlist Error

### ISSUE THREAD

**Issue by Klauditha** [Klauditha/desafio_proyecto_final#71]
Se borran la lista de deseos

**Comment by enlorca** [comment]
En Wishlist.jsx, fijarse en la linea 12. Para pruebas, mientras no implementemos el getBooks con el backend, se debe reemplazar book.book_id por book.bookId por que sigue usando el JSON anterior

![image](https://github.com/Klauditha/desafio_proyecto_final/assets/132632580/520bdc43-f336-4c32-b395-7f5065e9927d)
