### ISSUE TITLE
Habilitar render con BDD

### ISSUE THREAD

**Issue by Klauditha** [Klauditha/desafio_proyecto_final#77]

**Comment by enlorca** [comment]
Servidor de mi lado montado. Falta verificar que funcione correctamente

**Comment by Klauditha** [comment]
Datos de conexión

PGPASSWORD=XPteJDfN2ltQAGBxpIffN71bz2n8zT13 psql -h dpg-cnuf5efjbltc73c3l020-a.oregon-postgres.render.com -U root dbname_c17b
