### ISSUE TITLE
Autenticación y autorizacion de usuarios con JWT (Backend) - Requerimiento 3

### ISSUE THREAD

**Issue by enlorca** [Klauditha/desafio_proyecto_final#78]
> Requerimiento 3. Implementar la autenticación y autorización de usuarios con JWT.(2 Puntos)

**Comment by Klauditha** [comment]
@enlorca El proyecto BackEnd ya tiene un archivo con un metodo 'auth.handler.js'
Por si te sirve 👍 
<img width="442" alt="image" src="https://github.com/Klauditha/desafio_proyecto_final/assets/3738243/a343de2e-b3c9-4685-91a7-d78689367f82">

**Comment by enlorca** [comment]
> @enlorca El proyecto BackEnd ya tiene un archivo con un metodo 'auth.handler.js' Por si te sirve 👍 <img alt="image" width="442" src="https://private-user-images.githubusercontent.com/3738243/315859751-a343de2e-b3c9-4685-91a7-d78689367f82.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwNzMxMzgsIm5iZiI6MTcxMTA3MjgzOCwicGF0aCI6Ii8zNzM4MjQzLzMxNTg1OTc1MS1hMzQzZGUyZS1iM2M5LTQ2ODUtOTFhNy1kNzg2ODkzNjdmODIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjJUMDIwMDM4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDIxM2IzYWRlY2E2NzY3ODk4MmQ5MjdlMzFhMTZmZjIwYzE2ODNhNjJjM2I1MDgyODBiNmE0MTUyNWQyM2QwMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.dozOQWgpPnQYRb5cAYbSwBrlqbHcWTdj7ABoEEGtIZg">

Esto ahorra mucho, muchas gracias
