### ISSUE TITLE
Componente item Perfil de usuario

### ISSUE THREAD

**Issue by Klauditha** [Klauditha/desafio_proyecto_final#9]
![Image](https://github.com/Klauditha/desafio_proyecto_final/assets/3738243/d06c1380-22d7-41ac-b8ee-38a9a5a566df)

**Comment by orlandoflowers** [comment]
Pendiente popular de acuerdo al id del usuario loggeado @Klauditha @enlorca (No editable por ahora, solo para leer de acuerdo a como uno se registró)
